name: Backend CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore src.sln

      - name: Build
        run: dotnet build src.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src.sln --configuration Release --no-build

      - name: Build Docker Image
        run: docker build -t loan-api ./Fundo.Applications.WebApi